version: 2.1

jobs:
  run-tox:
    docker:
      - image: kuralabs/python3-dev:latest
    steps:
      - checkout
      - run:
          command: tox --recreate
          name: Running Tox

workflows:
  main:
    jobs:
      - run-tox
